#!/bin/bash
#
# nombre              : reindex-ldap
# descripción         : Reindexar LDAP
# autor               : Esteban M. Navas Martín
# fecha creación      : 30032017
# última modificación : 30032017
# uso                 : reindex-ldap
# instalación         : Guardar en  /usr/local/sbin/
# sugerencia          : Programar tarea cron:
#                       00 9    * * 7   root    /usr/local/sbin/reindex-ldap

#
# Copyright 2015, Esteban M. Navas Martín <algodelinux@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.
#

slapindex -vF /etc/ldap/slapd.d

